//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NS_WS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_GUITARE", Namespace="http://tempuri.org/")]
    public partial class C_GUITARE : object
    {
        
        private int idGuitareField;
        
        private string NomField;
        
        private string EtatField;
        
        private int idMicrophone_NeckField;
        
        private System.Nullable<int> idMicrophone_CentraleField;
        
        private int idVibratoField;
        
        private System.Nullable<int> idClientField;
        
        private int idMicrophone_BridgeField;
        
        private int idBois_MancheField;
        
        private int idBois_CorpsField;
        
        private int idBois_ToucheField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idGuitare
        {
            get
            {
                return this.idGuitareField;
            }
            set
            {
                this.idGuitareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Etat
        {
            get
            {
                return this.EtatField;
            }
            set
            {
                this.EtatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int idMicrophone_Neck
        {
            get
            {
                return this.idMicrophone_NeckField;
            }
            set
            {
                this.idMicrophone_NeckField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> idMicrophone_Centrale
        {
            get
            {
                return this.idMicrophone_CentraleField;
            }
            set
            {
                this.idMicrophone_CentraleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int idVibrato
        {
            get
            {
                return this.idVibratoField;
            }
            set
            {
                this.idVibratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> idClient
        {
            get
            {
                return this.idClientField;
            }
            set
            {
                this.idClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int idMicrophone_Bridge
        {
            get
            {
                return this.idMicrophone_BridgeField;
            }
            set
            {
                this.idMicrophone_BridgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int idBois_Manche
        {
            get
            {
                return this.idBois_MancheField;
            }
            set
            {
                this.idBois_MancheField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int idBois_Corps
        {
            get
            {
                return this.idBois_CorpsField;
            }
            set
            {
                this.idBois_CorpsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int idBois_Touche
        {
            get
            {
                return this.idBois_ToucheField;
            }
            set
            {
                this.idBois_ToucheField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_BOIS", Namespace="http://tempuri.org/")]
    public partial class C_BOIS : object
    {
        
        private int idBoisField;
        
        private string NomField;
        
        private string OrigineField;
        
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idBois
        {
            get
            {
                return this.idBoisField;
            }
            set
            {
                this.idBoisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Origine
        {
            get
            {
                return this.OrigineField;
            }
            set
            {
                this.OrigineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_MICROPHONE", Namespace="http://tempuri.org/")]
    public partial class C_MICROPHONE : object
    {
        
        private int idMicrophoneField;
        
        private string NomField;
        
        private string Reference_ConstruceteurField;
        
        private string MarqueField;
        
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idMicrophone
        {
            get
            {
                return this.idMicrophoneField;
            }
            set
            {
                this.idMicrophoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Reference_Construceteur
        {
            get
            {
                return this.Reference_ConstruceteurField;
            }
            set
            {
                this.Reference_ConstruceteurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Marque
        {
            get
            {
                return this.MarqueField;
            }
            set
            {
                this.MarqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_VIBRATO", Namespace="http://tempuri.org/")]
    public partial class C_VIBRATO : object
    {
        
        private int idVibratoField;
        
        private string NomField;
        
        private string ModeleField;
        
        private string MarqueField;
        
        private System.Nullable<int> StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idVibrato
        {
            get
            {
                return this.idVibratoField;
            }
            set
            {
                this.idVibratoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Modele
        {
            get
            {
                return this.ModeleField;
            }
            set
            {
                this.ModeleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Marque
        {
            get
            {
                return this.MarqueField;
            }
            set
            {
                this.MarqueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NS_WS.WS_GUITARESoap")]
    public interface WS_GUITARESoap
    {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Guitare", ReplyAction="*")]
        NS_WS.Add_GuitareResponse Add_Guitare(NS_WS.Add_GuitareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Guitare", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Add_GuitareResponse> Add_GuitareAsync(NS_WS.Add_GuitareRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Client", ReplyAction="*")]
        NS_WS.Add_ClientResponse Add_Client(NS_WS.Add_ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Client", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Add_ClientResponse> Add_ClientAsync(NS_WS.Add_ClientRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Vibrato", ReplyAction="*")]
        NS_WS.Add_VibratoResponse Add_Vibrato(NS_WS.Add_VibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Vibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Add_VibratoResponse> Add_VibratoAsync(NS_WS.Add_VibratoRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Bois", ReplyAction="*")]
        NS_WS.Add_BoisResponse Add_Bois(NS_WS.Add_BoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Bois", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Add_BoisResponse> Add_BoisAsync(NS_WS.Add_BoisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Microphone", ReplyAction="*")]
        NS_WS.Add_MicrophoneResponse Add_Microphone(NS_WS.Add_MicrophoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Microphone", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Add_MicrophoneResponse> Add_MicrophoneAsync(NS_WS.Add_MicrophoneRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Select_GuitareResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Guitare", ReplyAction="*")]
        NS_WS.Select_GuitareResponse Select_Guitare(NS_WS.Select_GuitareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_Guitare", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Select_GuitareResponse> Select_GuitareAsync(NS_WS.Select_GuitareRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetBoisResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBois", ReplyAction="*")]
        NS_WS.GetBoisResponse GetBois(NS_WS.GetBoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBois", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.GetBoisResponse> GetBoisAsync(NS_WS.GetBoisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetMicroResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMicro", ReplyAction="*")]
        NS_WS.GetMicroResponse GetMicro(NS_WS.GetMicroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMicro", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.GetMicroResponse> GetMicroAsync(NS_WS.GetMicroRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetVibratoResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVibrato", ReplyAction="*")]
        NS_WS.GetVibratoResponse GetVibrato(NS_WS.GetVibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.GetVibratoResponse> GetVibratoAsync(NS_WS.GetVibratoRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit_Bois", ReplyAction="*")]
        NS_WS.Edit_BoisResponse Edit_Bois(NS_WS.Edit_BoisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit_Bois", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Edit_BoisResponse> Edit_BoisAsync(NS_WS.Edit_BoisRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit_Micro", ReplyAction="*")]
        NS_WS.Edit_MicroResponse Edit_Micro(NS_WS.Edit_MicroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit_Micro", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Edit_MicroResponse> Edit_MicroAsync(NS_WS.Edit_MicroRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_Nom de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit_Vibrato", ReplyAction="*")]
        NS_WS.Edit_VibratoResponse Edit_Vibrato(NS_WS.Edit_VibratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit_Vibrato", ReplyAction="*")]
        System.Threading.Tasks.Task<NS_WS.Edit_VibratoResponse> Edit_VibratoAsync(NS_WS.Edit_VibratoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_GuitareRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Guitare", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_GuitareRequestBody Body;
        
        public Add_GuitareRequest()
        {
        }
        
        public Add_GuitareRequest(NS_WS.Add_GuitareRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_GuitareRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_Etat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int P_idMicrophoneNeck;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int P_idMicrophoneCentrale;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int P_Vibrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int P_Client;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int P_idMicrophoneBridge;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int P_idBoisManche;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int P_idBoisCorps;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int P_idBoisTouche;
        
        public Add_GuitareRequestBody()
        {
        }
        
        public Add_GuitareRequestBody(string P_Nom, string P_Etat, int P_idMicrophoneNeck, int P_idMicrophoneCentrale, int P_Vibrato, int P_Client, int P_idMicrophoneBridge, int P_idBoisManche, int P_idBoisCorps, int P_idBoisTouche)
        {
            this.P_Nom = P_Nom;
            this.P_Etat = P_Etat;
            this.P_idMicrophoneNeck = P_idMicrophoneNeck;
            this.P_idMicrophoneCentrale = P_idMicrophoneCentrale;
            this.P_Vibrato = P_Vibrato;
            this.P_Client = P_Client;
            this.P_idMicrophoneBridge = P_idMicrophoneBridge;
            this.P_idBoisManche = P_idBoisManche;
            this.P_idBoisCorps = P_idBoisCorps;
            this.P_idBoisTouche = P_idBoisTouche;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_GuitareResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_GuitareResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_GuitareResponseBody Body;
        
        public Add_GuitareResponse()
        {
        }
        
        public Add_GuitareResponse(NS_WS.Add_GuitareResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Add_GuitareResponseBody
    {
        
        public Add_GuitareResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_ClientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Client", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_ClientRequestBody Body;
        
        public Add_ClientRequest()
        {
        }
        
        public Add_ClientRequest(NS_WS.Add_ClientRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_ClientRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_Prenom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_Adresse;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string P_MotDePasse;
        
        public Add_ClientRequestBody()
        {
        }
        
        public Add_ClientRequestBody(string P_Nom, string P_Prenom, string P_Adresse, string P_MotDePasse)
        {
            this.P_Nom = P_Nom;
            this.P_Prenom = P_Prenom;
            this.P_Adresse = P_Adresse;
            this.P_MotDePasse = P_MotDePasse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_ClientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_ClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_ClientResponseBody Body;
        
        public Add_ClientResponse()
        {
        }
        
        public Add_ClientResponse(NS_WS.Add_ClientResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Add_ClientResponseBody
    {
        
        public Add_ClientResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_VibratoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Vibrato", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_VibratoRequestBody Body;
        
        public Add_VibratoRequest()
        {
        }
        
        public Add_VibratoRequest(NS_WS.Add_VibratoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_VibratoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_Modele;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_Marque;
        
        public Add_VibratoRequestBody()
        {
        }
        
        public Add_VibratoRequestBody(string P_Nom, string P_Modele, string P_Marque)
        {
            this.P_Nom = P_Nom;
            this.P_Modele = P_Modele;
            this.P_Marque = P_Marque;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_VibratoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_VibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_VibratoResponseBody Body;
        
        public Add_VibratoResponse()
        {
        }
        
        public Add_VibratoResponse(NS_WS.Add_VibratoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Add_VibratoResponseBody
    {
        
        public Add_VibratoResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_BoisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Bois", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_BoisRequestBody Body;
        
        public Add_BoisRequest()
        {
        }
        
        public Add_BoisRequest(NS_WS.Add_BoisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_BoisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_Origine;
        
        public Add_BoisRequestBody()
        {
        }
        
        public Add_BoisRequestBody(string P_Nom, string P_Origine)
        {
            this.P_Nom = P_Nom;
            this.P_Origine = P_Origine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_BoisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_BoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_BoisResponseBody Body;
        
        public Add_BoisResponse()
        {
        }
        
        public Add_BoisResponse(NS_WS.Add_BoisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Add_BoisResponseBody
    {
        
        public Add_BoisResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_MicrophoneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Microphone", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_MicrophoneRequestBody Body;
        
        public Add_MicrophoneRequest()
        {
        }
        
        public Add_MicrophoneRequest(NS_WS.Add_MicrophoneRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_MicrophoneRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_ReferenceConstructeur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_Marque;
        
        public Add_MicrophoneRequestBody()
        {
        }
        
        public Add_MicrophoneRequestBody(string P_Nom, string P_ReferenceConstructeur, string P_Marque)
        {
            this.P_Nom = P_Nom;
            this.P_ReferenceConstructeur = P_ReferenceConstructeur;
            this.P_Marque = P_Marque;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_MicrophoneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_MicrophoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Add_MicrophoneResponseBody Body;
        
        public Add_MicrophoneResponse()
        {
        }
        
        public Add_MicrophoneResponse(NS_WS.Add_MicrophoneResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Add_MicrophoneResponseBody
    {
        
        public Add_MicrophoneResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Select_GuitareRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select_Guitare", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Select_GuitareRequestBody Body;
        
        public Select_GuitareRequest()
        {
        }
        
        public Select_GuitareRequest(NS_WS.Select_GuitareRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Select_GuitareRequestBody
    {
        
        public Select_GuitareRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Select_GuitareResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select_GuitareResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Select_GuitareResponseBody Body;
        
        public Select_GuitareResponse()
        {
        }
        
        public Select_GuitareResponse(NS_WS.Select_GuitareResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Select_GuitareResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NS_WS.C_GUITARE[] Select_GuitareResult;
        
        public Select_GuitareResponseBody()
        {
        }
        
        public Select_GuitareResponseBody(NS_WS.C_GUITARE[] Select_GuitareResult)
        {
            this.Select_GuitareResult = Select_GuitareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBois", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.GetBoisRequestBody Body;
        
        public GetBoisRequest()
        {
        }
        
        public GetBoisRequest(NS_WS.GetBoisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBoisRequestBody
    {
        
        public GetBoisRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBoisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.GetBoisResponseBody Body;
        
        public GetBoisResponse()
        {
        }
        
        public GetBoisResponse(NS_WS.GetBoisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBoisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NS_WS.C_BOIS[] GetBoisResult;
        
        public GetBoisResponseBody()
        {
        }
        
        public GetBoisResponseBody(NS_WS.C_BOIS[] GetBoisResult)
        {
            this.GetBoisResult = GetBoisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMicroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMicro", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.GetMicroRequestBody Body;
        
        public GetMicroRequest()
        {
        }
        
        public GetMicroRequest(NS_WS.GetMicroRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMicroRequestBody
    {
        
        public GetMicroRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMicroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMicroResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.GetMicroResponseBody Body;
        
        public GetMicroResponse()
        {
        }
        
        public GetMicroResponse(NS_WS.GetMicroResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMicroResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NS_WS.C_MICROPHONE[] GetMicroResult;
        
        public GetMicroResponseBody()
        {
        }
        
        public GetMicroResponseBody(NS_WS.C_MICROPHONE[] GetMicroResult)
        {
            this.GetMicroResult = GetMicroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVibratoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVibrato", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.GetVibratoRequestBody Body;
        
        public GetVibratoRequest()
        {
        }
        
        public GetVibratoRequest(NS_WS.GetVibratoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVibratoRequestBody
    {
        
        public GetVibratoRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVibratoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.GetVibratoResponseBody Body;
        
        public GetVibratoResponse()
        {
        }
        
        public GetVibratoResponse(NS_WS.GetVibratoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVibratoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NS_WS.C_VIBRATO[] GetVibratoResult;
        
        public GetVibratoResponseBody()
        {
        }
        
        public GetVibratoResponseBody(NS_WS.C_VIBRATO[] GetVibratoResult)
        {
            this.GetVibratoResult = GetVibratoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Edit_BoisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit_Bois", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Edit_BoisRequestBody Body;
        
        public Edit_BoisRequest()
        {
        }
        
        public Edit_BoisRequest(NS_WS.Edit_BoisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Edit_BoisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int P_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_Origine;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int P_Stock;
        
        public Edit_BoisRequestBody()
        {
        }
        
        public Edit_BoisRequestBody(int P_Id, string P_Nom, string P_Origine, int P_Stock)
        {
            this.P_Id = P_Id;
            this.P_Nom = P_Nom;
            this.P_Origine = P_Origine;
            this.P_Stock = P_Stock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Edit_BoisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit_BoisResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Edit_BoisResponseBody Body;
        
        public Edit_BoisResponse()
        {
        }
        
        public Edit_BoisResponse(NS_WS.Edit_BoisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Edit_BoisResponseBody
    {
        
        public Edit_BoisResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Edit_MicroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit_Micro", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Edit_MicroRequestBody Body;
        
        public Edit_MicroRequest()
        {
        }
        
        public Edit_MicroRequest(NS_WS.Edit_MicroRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Edit_MicroRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int P_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_Reference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string P_Marque;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int P_Stock;
        
        public Edit_MicroRequestBody()
        {
        }
        
        public Edit_MicroRequestBody(int P_Id, string P_Nom, string P_Reference, string P_Marque, int P_Stock)
        {
            this.P_Id = P_Id;
            this.P_Nom = P_Nom;
            this.P_Reference = P_Reference;
            this.P_Marque = P_Marque;
            this.P_Stock = P_Stock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Edit_MicroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit_MicroResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Edit_MicroResponseBody Body;
        
        public Edit_MicroResponse()
        {
        }
        
        public Edit_MicroResponse(NS_WS.Edit_MicroResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Edit_MicroResponseBody
    {
        
        public Edit_MicroResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Edit_VibratoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit_Vibrato", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Edit_VibratoRequestBody Body;
        
        public Edit_VibratoRequest()
        {
        }
        
        public Edit_VibratoRequest(NS_WS.Edit_VibratoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Edit_VibratoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int P_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string P_Nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string P_Modele;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string P_Marque;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int P_Stock;
        
        public Edit_VibratoRequestBody()
        {
        }
        
        public Edit_VibratoRequestBody(int P_Id, string P_Nom, string P_Modele, string P_Marque, int P_Stock)
        {
            this.P_Id = P_Id;
            this.P_Nom = P_Nom;
            this.P_Modele = P_Modele;
            this.P_Marque = P_Marque;
            this.P_Stock = P_Stock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Edit_VibratoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit_VibratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NS_WS.Edit_VibratoResponseBody Body;
        
        public Edit_VibratoResponse()
        {
        }
        
        public Edit_VibratoResponse(NS_WS.Edit_VibratoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Edit_VibratoResponseBody
    {
        
        public Edit_VibratoResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WS_GUITARESoapChannel : NS_WS.WS_GUITARESoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WS_GUITARESoapClient : System.ServiceModel.ClientBase<NS_WS.WS_GUITARESoap>, NS_WS.WS_GUITARESoap
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_GUITARESoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_GUITARESoapClient.GetBindingForEndpoint(endpointConfiguration), WS_GUITARESoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_GUITARESoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_GUITARESoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_GUITARESoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_GUITARESoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_GUITARESoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Add_GuitareResponse NS_WS.WS_GUITARESoap.Add_Guitare(NS_WS.Add_GuitareRequest request)
        {
            return base.Channel.Add_Guitare(request);
        }
        
        public void Add_Guitare(string P_Nom, string P_Etat, int P_idMicrophoneNeck, int P_idMicrophoneCentrale, int P_Vibrato, int P_Client, int P_idMicrophoneBridge, int P_idBoisManche, int P_idBoisCorps, int P_idBoisTouche)
        {
            NS_WS.Add_GuitareRequest inValue = new NS_WS.Add_GuitareRequest();
            inValue.Body = new NS_WS.Add_GuitareRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Etat = P_Etat;
            inValue.Body.P_idMicrophoneNeck = P_idMicrophoneNeck;
            inValue.Body.P_idMicrophoneCentrale = P_idMicrophoneCentrale;
            inValue.Body.P_Vibrato = P_Vibrato;
            inValue.Body.P_Client = P_Client;
            inValue.Body.P_idMicrophoneBridge = P_idMicrophoneBridge;
            inValue.Body.P_idBoisManche = P_idBoisManche;
            inValue.Body.P_idBoisCorps = P_idBoisCorps;
            inValue.Body.P_idBoisTouche = P_idBoisTouche;
            NS_WS.Add_GuitareResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Add_Guitare(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Add_GuitareResponse> NS_WS.WS_GUITARESoap.Add_GuitareAsync(NS_WS.Add_GuitareRequest request)
        {
            return base.Channel.Add_GuitareAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Add_GuitareResponse> Add_GuitareAsync(string P_Nom, string P_Etat, int P_idMicrophoneNeck, int P_idMicrophoneCentrale, int P_Vibrato, int P_Client, int P_idMicrophoneBridge, int P_idBoisManche, int P_idBoisCorps, int P_idBoisTouche)
        {
            NS_WS.Add_GuitareRequest inValue = new NS_WS.Add_GuitareRequest();
            inValue.Body = new NS_WS.Add_GuitareRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Etat = P_Etat;
            inValue.Body.P_idMicrophoneNeck = P_idMicrophoneNeck;
            inValue.Body.P_idMicrophoneCentrale = P_idMicrophoneCentrale;
            inValue.Body.P_Vibrato = P_Vibrato;
            inValue.Body.P_Client = P_Client;
            inValue.Body.P_idMicrophoneBridge = P_idMicrophoneBridge;
            inValue.Body.P_idBoisManche = P_idBoisManche;
            inValue.Body.P_idBoisCorps = P_idBoisCorps;
            inValue.Body.P_idBoisTouche = P_idBoisTouche;
            return ((NS_WS.WS_GUITARESoap)(this)).Add_GuitareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Add_ClientResponse NS_WS.WS_GUITARESoap.Add_Client(NS_WS.Add_ClientRequest request)
        {
            return base.Channel.Add_Client(request);
        }
        
        public void Add_Client(string P_Nom, string P_Prenom, string P_Adresse, string P_MotDePasse)
        {
            NS_WS.Add_ClientRequest inValue = new NS_WS.Add_ClientRequest();
            inValue.Body = new NS_WS.Add_ClientRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Prenom = P_Prenom;
            inValue.Body.P_Adresse = P_Adresse;
            inValue.Body.P_MotDePasse = P_MotDePasse;
            NS_WS.Add_ClientResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Add_Client(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Add_ClientResponse> NS_WS.WS_GUITARESoap.Add_ClientAsync(NS_WS.Add_ClientRequest request)
        {
            return base.Channel.Add_ClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Add_ClientResponse> Add_ClientAsync(string P_Nom, string P_Prenom, string P_Adresse, string P_MotDePasse)
        {
            NS_WS.Add_ClientRequest inValue = new NS_WS.Add_ClientRequest();
            inValue.Body = new NS_WS.Add_ClientRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Prenom = P_Prenom;
            inValue.Body.P_Adresse = P_Adresse;
            inValue.Body.P_MotDePasse = P_MotDePasse;
            return ((NS_WS.WS_GUITARESoap)(this)).Add_ClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Add_VibratoResponse NS_WS.WS_GUITARESoap.Add_Vibrato(NS_WS.Add_VibratoRequest request)
        {
            return base.Channel.Add_Vibrato(request);
        }
        
        public void Add_Vibrato(string P_Nom, string P_Modele, string P_Marque)
        {
            NS_WS.Add_VibratoRequest inValue = new NS_WS.Add_VibratoRequest();
            inValue.Body = new NS_WS.Add_VibratoRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Modele = P_Modele;
            inValue.Body.P_Marque = P_Marque;
            NS_WS.Add_VibratoResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Add_Vibrato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Add_VibratoResponse> NS_WS.WS_GUITARESoap.Add_VibratoAsync(NS_WS.Add_VibratoRequest request)
        {
            return base.Channel.Add_VibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Add_VibratoResponse> Add_VibratoAsync(string P_Nom, string P_Modele, string P_Marque)
        {
            NS_WS.Add_VibratoRequest inValue = new NS_WS.Add_VibratoRequest();
            inValue.Body = new NS_WS.Add_VibratoRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Modele = P_Modele;
            inValue.Body.P_Marque = P_Marque;
            return ((NS_WS.WS_GUITARESoap)(this)).Add_VibratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Add_BoisResponse NS_WS.WS_GUITARESoap.Add_Bois(NS_WS.Add_BoisRequest request)
        {
            return base.Channel.Add_Bois(request);
        }
        
        public void Add_Bois(string P_Nom, string P_Origine)
        {
            NS_WS.Add_BoisRequest inValue = new NS_WS.Add_BoisRequest();
            inValue.Body = new NS_WS.Add_BoisRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Origine = P_Origine;
            NS_WS.Add_BoisResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Add_Bois(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Add_BoisResponse> NS_WS.WS_GUITARESoap.Add_BoisAsync(NS_WS.Add_BoisRequest request)
        {
            return base.Channel.Add_BoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Add_BoisResponse> Add_BoisAsync(string P_Nom, string P_Origine)
        {
            NS_WS.Add_BoisRequest inValue = new NS_WS.Add_BoisRequest();
            inValue.Body = new NS_WS.Add_BoisRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Origine = P_Origine;
            return ((NS_WS.WS_GUITARESoap)(this)).Add_BoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Add_MicrophoneResponse NS_WS.WS_GUITARESoap.Add_Microphone(NS_WS.Add_MicrophoneRequest request)
        {
            return base.Channel.Add_Microphone(request);
        }
        
        public void Add_Microphone(string P_Nom, string P_ReferenceConstructeur, string P_Marque)
        {
            NS_WS.Add_MicrophoneRequest inValue = new NS_WS.Add_MicrophoneRequest();
            inValue.Body = new NS_WS.Add_MicrophoneRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_ReferenceConstructeur = P_ReferenceConstructeur;
            inValue.Body.P_Marque = P_Marque;
            NS_WS.Add_MicrophoneResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Add_Microphone(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Add_MicrophoneResponse> NS_WS.WS_GUITARESoap.Add_MicrophoneAsync(NS_WS.Add_MicrophoneRequest request)
        {
            return base.Channel.Add_MicrophoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Add_MicrophoneResponse> Add_MicrophoneAsync(string P_Nom, string P_ReferenceConstructeur, string P_Marque)
        {
            NS_WS.Add_MicrophoneRequest inValue = new NS_WS.Add_MicrophoneRequest();
            inValue.Body = new NS_WS.Add_MicrophoneRequestBody();
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_ReferenceConstructeur = P_ReferenceConstructeur;
            inValue.Body.P_Marque = P_Marque;
            return ((NS_WS.WS_GUITARESoap)(this)).Add_MicrophoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Select_GuitareResponse NS_WS.WS_GUITARESoap.Select_Guitare(NS_WS.Select_GuitareRequest request)
        {
            return base.Channel.Select_Guitare(request);
        }
        
        public NS_WS.C_GUITARE[] Select_Guitare()
        {
            NS_WS.Select_GuitareRequest inValue = new NS_WS.Select_GuitareRequest();
            inValue.Body = new NS_WS.Select_GuitareRequestBody();
            NS_WS.Select_GuitareResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Select_Guitare(inValue);
            return retVal.Body.Select_GuitareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Select_GuitareResponse> NS_WS.WS_GUITARESoap.Select_GuitareAsync(NS_WS.Select_GuitareRequest request)
        {
            return base.Channel.Select_GuitareAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Select_GuitareResponse> Select_GuitareAsync()
        {
            NS_WS.Select_GuitareRequest inValue = new NS_WS.Select_GuitareRequest();
            inValue.Body = new NS_WS.Select_GuitareRequestBody();
            return ((NS_WS.WS_GUITARESoap)(this)).Select_GuitareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.GetBoisResponse NS_WS.WS_GUITARESoap.GetBois(NS_WS.GetBoisRequest request)
        {
            return base.Channel.GetBois(request);
        }
        
        public NS_WS.C_BOIS[] GetBois()
        {
            NS_WS.GetBoisRequest inValue = new NS_WS.GetBoisRequest();
            inValue.Body = new NS_WS.GetBoisRequestBody();
            NS_WS.GetBoisResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).GetBois(inValue);
            return retVal.Body.GetBoisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.GetBoisResponse> NS_WS.WS_GUITARESoap.GetBoisAsync(NS_WS.GetBoisRequest request)
        {
            return base.Channel.GetBoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.GetBoisResponse> GetBoisAsync()
        {
            NS_WS.GetBoisRequest inValue = new NS_WS.GetBoisRequest();
            inValue.Body = new NS_WS.GetBoisRequestBody();
            return ((NS_WS.WS_GUITARESoap)(this)).GetBoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.GetMicroResponse NS_WS.WS_GUITARESoap.GetMicro(NS_WS.GetMicroRequest request)
        {
            return base.Channel.GetMicro(request);
        }
        
        public NS_WS.C_MICROPHONE[] GetMicro()
        {
            NS_WS.GetMicroRequest inValue = new NS_WS.GetMicroRequest();
            inValue.Body = new NS_WS.GetMicroRequestBody();
            NS_WS.GetMicroResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).GetMicro(inValue);
            return retVal.Body.GetMicroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.GetMicroResponse> NS_WS.WS_GUITARESoap.GetMicroAsync(NS_WS.GetMicroRequest request)
        {
            return base.Channel.GetMicroAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.GetMicroResponse> GetMicroAsync()
        {
            NS_WS.GetMicroRequest inValue = new NS_WS.GetMicroRequest();
            inValue.Body = new NS_WS.GetMicroRequestBody();
            return ((NS_WS.WS_GUITARESoap)(this)).GetMicroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.GetVibratoResponse NS_WS.WS_GUITARESoap.GetVibrato(NS_WS.GetVibratoRequest request)
        {
            return base.Channel.GetVibrato(request);
        }
        
        public NS_WS.C_VIBRATO[] GetVibrato()
        {
            NS_WS.GetVibratoRequest inValue = new NS_WS.GetVibratoRequest();
            inValue.Body = new NS_WS.GetVibratoRequestBody();
            NS_WS.GetVibratoResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).GetVibrato(inValue);
            return retVal.Body.GetVibratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.GetVibratoResponse> NS_WS.WS_GUITARESoap.GetVibratoAsync(NS_WS.GetVibratoRequest request)
        {
            return base.Channel.GetVibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.GetVibratoResponse> GetVibratoAsync()
        {
            NS_WS.GetVibratoRequest inValue = new NS_WS.GetVibratoRequest();
            inValue.Body = new NS_WS.GetVibratoRequestBody();
            return ((NS_WS.WS_GUITARESoap)(this)).GetVibratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Edit_BoisResponse NS_WS.WS_GUITARESoap.Edit_Bois(NS_WS.Edit_BoisRequest request)
        {
            return base.Channel.Edit_Bois(request);
        }
        
        public void Edit_Bois(int P_Id, string P_Nom, string P_Origine, int P_Stock)
        {
            NS_WS.Edit_BoisRequest inValue = new NS_WS.Edit_BoisRequest();
            inValue.Body = new NS_WS.Edit_BoisRequestBody();
            inValue.Body.P_Id = P_Id;
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Origine = P_Origine;
            inValue.Body.P_Stock = P_Stock;
            NS_WS.Edit_BoisResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Edit_Bois(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Edit_BoisResponse> NS_WS.WS_GUITARESoap.Edit_BoisAsync(NS_WS.Edit_BoisRequest request)
        {
            return base.Channel.Edit_BoisAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Edit_BoisResponse> Edit_BoisAsync(int P_Id, string P_Nom, string P_Origine, int P_Stock)
        {
            NS_WS.Edit_BoisRequest inValue = new NS_WS.Edit_BoisRequest();
            inValue.Body = new NS_WS.Edit_BoisRequestBody();
            inValue.Body.P_Id = P_Id;
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Origine = P_Origine;
            inValue.Body.P_Stock = P_Stock;
            return ((NS_WS.WS_GUITARESoap)(this)).Edit_BoisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Edit_MicroResponse NS_WS.WS_GUITARESoap.Edit_Micro(NS_WS.Edit_MicroRequest request)
        {
            return base.Channel.Edit_Micro(request);
        }
        
        public void Edit_Micro(int P_Id, string P_Nom, string P_Reference, string P_Marque, int P_Stock)
        {
            NS_WS.Edit_MicroRequest inValue = new NS_WS.Edit_MicroRequest();
            inValue.Body = new NS_WS.Edit_MicroRequestBody();
            inValue.Body.P_Id = P_Id;
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Reference = P_Reference;
            inValue.Body.P_Marque = P_Marque;
            inValue.Body.P_Stock = P_Stock;
            NS_WS.Edit_MicroResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Edit_Micro(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Edit_MicroResponse> NS_WS.WS_GUITARESoap.Edit_MicroAsync(NS_WS.Edit_MicroRequest request)
        {
            return base.Channel.Edit_MicroAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Edit_MicroResponse> Edit_MicroAsync(int P_Id, string P_Nom, string P_Reference, string P_Marque, int P_Stock)
        {
            NS_WS.Edit_MicroRequest inValue = new NS_WS.Edit_MicroRequest();
            inValue.Body = new NS_WS.Edit_MicroRequestBody();
            inValue.Body.P_Id = P_Id;
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Reference = P_Reference;
            inValue.Body.P_Marque = P_Marque;
            inValue.Body.P_Stock = P_Stock;
            return ((NS_WS.WS_GUITARESoap)(this)).Edit_MicroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NS_WS.Edit_VibratoResponse NS_WS.WS_GUITARESoap.Edit_Vibrato(NS_WS.Edit_VibratoRequest request)
        {
            return base.Channel.Edit_Vibrato(request);
        }
        
        public void Edit_Vibrato(int P_Id, string P_Nom, string P_Modele, string P_Marque, int P_Stock)
        {
            NS_WS.Edit_VibratoRequest inValue = new NS_WS.Edit_VibratoRequest();
            inValue.Body = new NS_WS.Edit_VibratoRequestBody();
            inValue.Body.P_Id = P_Id;
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Modele = P_Modele;
            inValue.Body.P_Marque = P_Marque;
            inValue.Body.P_Stock = P_Stock;
            NS_WS.Edit_VibratoResponse retVal = ((NS_WS.WS_GUITARESoap)(this)).Edit_Vibrato(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NS_WS.Edit_VibratoResponse> NS_WS.WS_GUITARESoap.Edit_VibratoAsync(NS_WS.Edit_VibratoRequest request)
        {
            return base.Channel.Edit_VibratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NS_WS.Edit_VibratoResponse> Edit_VibratoAsync(int P_Id, string P_Nom, string P_Modele, string P_Marque, int P_Stock)
        {
            NS_WS.Edit_VibratoRequest inValue = new NS_WS.Edit_VibratoRequest();
            inValue.Body = new NS_WS.Edit_VibratoRequestBody();
            inValue.Body.P_Id = P_Id;
            inValue.Body.P_Nom = P_Nom;
            inValue.Body.P_Modele = P_Modele;
            inValue.Body.P_Marque = P_Marque;
            inValue.Body.P_Stock = P_Stock;
            return ((NS_WS.WS_GUITARESoap)(this)).Edit_VibratoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_GUITARESoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_GUITARESoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_GUITARESoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.2:9797/WS_GUITARE.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_GUITARESoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.2:9797/WS_GUITARE.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_GUITARESoap,
            
            WS_GUITARESoap12,
        }
    }
}
